################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
OBJS := 
SECONDARY_FLASH := 
SECONDARY_LIST := 
SECONDARY_SIZE := 
ASM_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
app/tlkapp_general \
core/B91 \
core \
tlkalg/audio/ec \
tlkalg/audio/eq \
tlkalg/audio/resample \
tlkapi \
tlkdev/ext \
tlkdev/sys \
tlkdev \
tlkdev/usr \
tlkdrv/B91 \
tlkdrv/B91/ext_driver/BQB \
tlkdrv/B91/ext_driver/BT \
tlkdrv/B91/ext_driver/EMI \
tlkdrv/B91/ext_driver/PA \
tlkdrv/B91/ext_driver/calibration \
tlkdrv/B91/ext_driver \
tlkdrv/B91/ext_driver/setting \
tlkdrv/ext/battery \
tlkdrv/ext/charge \
tlkdrv/ext/codec \
tlkdrv/ext/key \
tlkdrv/ext/keyboard \
tlkdrv/ext/lcd/st77903_data \
tlkdrv/ext/lcd \
tlkdrv/ext/led \
tlkdrv/ext/serial \
tlkdrv/ext/sram \
tlkdrv/ext/store \
tlkdrv/ext/touch \
tlkdrv/usr \
tlklib/cpc/cpc1 \
tlklib/cpc/cpc2 \
tlklib/cpc/cpc3 \
tlklib/cpc \
tlklib/dbg \
tlklib/fs/fatfs \
tlklib/fs \
tlklib/gui \
tlklib/ios/ams \
tlklib/ios/ancs \
tlklib/ios/ios_srvComm \
tlklib/mem \
tlklib/os/freertos \
tlklib/os/freertos/portable/GCC/RISC-V \
tlklib/os/freertos/portable/MemMang \
tlklib/os \
tlklib/usb/cdc \
tlklib/usb/hid \
tlklib/usb/msc \
tlklib/usb \
tlklib/usb/uac \
tlklib/usb/udb \
tlklib/usb/usr \
tlkmdi/aud \
tlkmdi/bt \
tlkmdi/gui \
tlkmdi/le \
tlkmdi/misc \
tlkmmi/audio \
tlkmmi/btmgr \
tlkmmi/debug \
tlkmmi/device \
tlkmmi/file \
tlkmmi/lemgr \
tlkmmi/phone \
tlkmmi/sensor \
tlkmmi/stack \
tlkmmi/system \
tlkmmi/test/ats \
tlkmmi/test/bqb \
tlkmmi/test/emi \
tlkmmi/test/fat \
tlkmmi/test/pts \
tlkmmi/test/rdt/bt \
tlkmmi/test/rdt/le \
tlkmmi/test/rdt/t001 \
tlkmmi/test/rdt/t002 \
tlkmmi/test/rdt/t003 \
tlkmmi/test/rdt/t005 \
tlkmmi/test/rdt \
tlkmmi/test \
tlkmmi/test/usr \
tlkmmi/view \
tlkstk/ble \
tlkstk/bt/bth \
tlkstk/bt/btp \
tlkstk/bt/btp/pts \
tlkstk/bt/btp/sdp \
tlkstk/bt/leh \
tlkstk/bt/lep \
tlkstk \
tlksys \

